name: Build Kernel a15-6-6

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Select KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select KSU branch"
        required: true
        type: choice
        options:
          - Stable(Standard)
          - Dev(Development)
          - Other(Other/Specified)
        default: Stable(Standard)
      version:
        description: 'Custom version name (e.g. located at 6.6.77-android15-8<custom-version>; leave empty to use default version)'
        required: false
        type: string
      build_time:
        description: 'Set kernel build time (format described in repository documentation)'
        required: false
        type: string
      use_zram:
        description: 'Enable additional ZRAM algorithms?'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: 'Enable BBG anti-brick patch? (Disable if errors occur)'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Enable KPM feature?'
        required: true
        type: boolean
        default: true
      supp_op:
        description: 'Enable OnePlus 8E processor device support? (No need to check for non-target devices)'
        required: false
        type: boolean
        default: false
      get_manager:
        description: 'Fetch the latest KSU Manager and SUS module?'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: 'Upload AK3 archive only? (No boot image, faster download)'
        required: false
        type: boolean
        default: false

jobs:

  build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_kpm: ${{ inputs.use_kpm }}
      supp_op: ${{ inputs.supp_op }}
      onlyAk3: ${{ inputs.onlyAk3 }}
      build_time: ${{ inputs.build_time }}
  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
